### ISSUE TITLE
Set responder state from parent

### ISSUE THREAD

**Issue by jeanbaptistebeau** [ricocrescenzio95/SUITextField#8]
If I have a custom class built on top of `SUITextField`:

```
struct OTextField: View {
    @Binding var text: String
    // ...

    var body: some View {
        SUITextField(text: $text)
        // ... bunch of modifiers
    }
}
```

I'd like to be able to set the responder modifier on the parent class:

```
    var body: some View {
            OTextField(text: $text)
                .responder($isFocused, equals: true)
    }

```

But it's not possible because `responder` is only a modifier for the `SUITextField` class. But looking at the implementation, I don't see any reason why it would not be possible to call it on a simple `View`?

You could simply add an extension:

```
extension View {
    
    func responder<Value>(_ binding: ResponderState<Value>.Binding, equals value: Value) -> some View where Value: Hashable {
        _ = binding.storage.values.insert(value)
        return self
            .environment(\.responderValue, value)
            .environment(\.responderStorage, binding.storage)
    }

}
```

I tried adding it to a local version and it seems to work well. Let me know if you want me to submit a PR.

**Comment by ricocrescenzio95** [comment]
This is interesting, I haven't thought this initially. I'll check your PR

**Comment by ricocrescenzio95** [comment]
Merged here https://github.com/ricocrescenzio95/SUITextField/pull/9
